### ISSUE TITLE
Fetching data from MongoDB

### ISSUE THREAD

**Issue by Piciu19** [Piciu19/LibrarianGUI#1]
### Tasks

- [x] Fetch active rents data from _MongoDB_
- [x] Display active rents data in TreeView
- [x] Fetch history rents data from _MongoDB_
- [x] Display history in TreeView
