### ISSUE TITLE
Make it pretty

### ISSUE THREAD

**Issue by Piciu19** [Piciu19/LibrarianGUI#11]
### Tasks

- [ ] Organize widgets on the main window
- [ ] Adjust size of the top windows and login window
- [ ] Add Sun Village theme

### Dependencies
- #
