### ISSUE TITLE
Books list

### ISSUE THREAD

**Issue by Piciu19** [Piciu19/LibrarianGUI#3]
### Tasks

- [ ] Fetch books list from _MongoDB_
- [ ] Edit books amount after adding rent
- [ ] Edit books amount after ending rent

### Dependencies
- #2
