### ISSUE TITLE
Software setup

### ISSUE THREAD

**Issue by Piciu19** [Piciu19/LibrarianGUI#7]
### Tasks

- [ ] Check if config YAML is set up
- [ ] Make console config window
- [ ] Option 1: Create new config
- [ ] Option 2: Import config from file

### Dependencies
- None
